version: "3.9"

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}

services:
  ui:
    image: node:20
    user: node
    working_dir: /home/node/app
    environment:
      BASE_PATH: /assets/app/
    ports:
      - 80:3000
    volumes:
      - ./:/home/node/app
    extra_hosts: # For Linux
      - host.docker.internal:host-gateway
    tty: true
    expose:
      - 3000
    command: "npm run dev"
