name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  CACHE_NAME: cache-maven-deps

jobs:
  lint-ts:
    name: Lint TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: lint-ts
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run build

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test
